.PHONY: clean All

All:
	@echo "----------Building project:[ exercise3 - Debug ]----------"
	@cd "exercise3" && "$(MAKE)" -f  "exercise3.mk"
clean:
	@echo "----------Cleaning project:[ exercise3 - Debug ]----------"
	@cd "exercise3" && "$(MAKE)" -f  "exercise3.mk" clean
