.PHONY: clean All

All:
	@echo "----------Building project:[ quiz - Debug ]----------"
	@"$(MAKE)" -f  "quiz.mk"
clean:
	@echo "----------Cleaning project:[ quiz - Debug ]----------"
	@"$(MAKE)" -f  "quiz.mk" clean
