.PHONY: clean All

All:
	@echo "----------Building project:[ tradingsystem - Debug ]----------"
	@"$(MAKE)" -f  "tradingsystem.mk"
clean:
	@echo "----------Cleaning project:[ tradingsystem - Debug ]----------"
	@"$(MAKE)" -f  "tradingsystem.mk" clean
