.PHONY: clean All

All:
	@echo "----------Building project:[ exercise1 - Debug ]----------"
	@cd "exercise1" && "$(MAKE)" -f  "exercise1.mk"
clean:
	@echo "----------Cleaning project:[ exercise1 - Debug ]----------"
	@cd "exercise1" && "$(MAKE)" -f  "exercise1.mk" clean
